.PHONY: run

# Edit DATA path
DATA=C:\VSC Omar\Data Mining\Data_mining_HWs\Homework2\Dataset\T10I4D100K.dat    #./T10I4D100K.dat
MIN_SUPPORT_PERCENT=1.0
MIN_CONF=0.5

run:
	python3 apriori.py --path "$(DATA)" --min_support_percent $(MIN_SUPPORT_PERCENT) --min_conf $(MIN_CONF)


