.PHONY: run

# Change DATA path
DATA=<"replace with path to dataset">
MIN_SUPPORT_PERCENT=3.0
MIN_CONF=0.5

run:
	python3 apriori.py --path "$(DATA)" --min_support_percent $(MIN_SUPPORT_PERCENT) --min_conf $(MIN_CONF)


